export const INFO_LOAD = 'INFO_LOAD';
export const INFO_LOAD_SUCCESS = 'INFO_LOAD_SUCCESS';
export const INFO_LOAD_FAILURE = 'INFO_LOAD_FAILURE';

export const INFO_RESET = 'INFO_RESET';

export const SHOWLIST_LOAD = 'SHOWLIST_LOAD';
export const SHOWLIST_LOAD_SUCCESS = 'SHOWLIST_LOAD_SUCCESS';
export const SHOWLIST_LOAD_FAILURE = 'SHOWLIST_LOAD_FAILURE';

export const SHOWLIST_RESET = 'SHOWLIST_RESET';

export const PLAYLIST_LOAD = 'PLAYLIST_LOAD';
export const PLAYLIST_LOAD_SUCCESS = 'PLAYLIST_LOAD_SUCCESS';
export const PLAYLIST_LOAD_FAILURE = 'PLAYLIST_LOAD_FAILURE';

export const PLAYLIST_RESET = 'PLAYLIST_RESET';
